# Generated by Django 2.2.5 on 2019-09-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rsaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicKey', models.CharField(max_length=500)),
                ('privateKey', models.CharField(max_length=500)),
                ('prime1', models.IntegerField()),
                ('prime2', models.IntegerField()),
                ('modulus', models.IntegerField()),
                ('totient', models.IntegerField()),
            ],
        ),
    ]
